### ISSUE TITLE
A threshold to remove the cell type with low proportion

### ISSUE THREAD

**Issue by jiawei-zhong** [almaan/stereoscope#13]
Hi Alma,

I observed that all spots have a proportion for each cell type. For example, if I input 5 cell types as annotation, the output will be:
|   | RGC | HC | Rod | Cone | Microgila |
| ------ | ------ |  ------ | ------ | ------ | ------ |
| AAACAAGTATCTCCCA-1 | 0.18 | 0.2 | 0.6 | 0.01 | 0.01 |

In this case, I will assume this spot have 3 cell type:  RGC, HC, Rod as Cone and Microgila have low proportions.

Just wanted to know that will you set a threshold to remove the low proportion cell type when deducing which cell types are in each spot? If yes, which threshold is appropriate? 0.05? 0.01?

Best regards,
Jiawei

**Comment by almaan** [comment]
Hello @jiawei-zhong 

happy to see you find `stereoscope` of interest to your analysis.

Your question is very relevant, and I would say that the answer depends on your data meaning that - unfortunately - there is no "standard threshold". Still, what I would recommend you to do is perhaps the following:

1. Estimate the approximate number of cells at each of your spots (capture locations). You could either use the estimate given by Visium (1-10 cells) per spot, or for example make a cell segmentation based on the HE-image to get a number more specific for your tissue. Whatever approach you decide upon, let's call the value you end up with `density`.

2. Set the threshold value to `1/density`. The reasoning being that if you expect it to be, for example, only 10 cells per spot; a proportion value of 0.0001 for a certain cell type would equal 10 * 0.0001 = 0.001 cells << 1 cell and hence could be considered as a negligible contribution.

There is a feature in the `stereoscope look` module that might interest you, namely the `--threshold` flag, which allows you to set a threshold value (like the one you requested above) and all values lower than this value will be greyed out in the visualization. Using this you can probe and test how certain threshold values would affect your data.

Best of luck
Alma
