### ISSUE TITLE
anndata support?

### ISSUE THREAD

**Issue by giovp** [almaan/stereoscope#4]
Hi Alma,

Hope to find you well !

we recently finalized support for visium in anndata. You can have a look at how to analyse visium data with scanpy+anndata [here](https://scanpy-tutorials.readthedocs.io/en/latest/spatial/basic-analysis.html) and [here](https://scanpy-tutorials.readthedocs.io/en/latest/spatial/integration-scanorama.html).

We are planned to release a new scanpy version by end of the week, so online docs will be updated by then. Meanwhile, you can have a look at how visium is stored in anndata [here](https://github.com/theislab/scanpy/blob/b1fdfc9fd176f7b3d8037b5b491e13fd6ddab5e5/scanpy/readwrite.py#L281).

I was wondering, do you still plan to provide anndata support for stereoscope? 
If yes, in what form? I was wondering whether having a basic API that allows users to run stereoscope from a notebook would make sense (essentially having stereoscope fully integrated in a scanpy pipeline). 

Let me know what you think! Happy to contribute on this! 

Best,
Giovanni

**Comment by almaan** [comment]
Hi Giovanni! 

That's great to hear! Stoked that Visium data is now compatible with anndata - and also interesting to see how you've approached how to keep multiple sections in the same anndata object! Also, thank you for the links - very informative.

To address you questions, yes this is very much on the todo list; my aim is to make stereoscope fully compatible with anndata files and also provide an API. I have some other projects that require my attention during May, but my estimate is that the anndata support/API should be in place by early June. I will for sure come back to you if there are any questions or such during that period!

**Comment by giovp** [comment]
That's great!
Thanks a lot and again happy to help in any way!
