### ISSUE TITLE
Setup numba didn't work

### ISSUE THREAD

**Issue by nik1sto** [almaan/stereoscope#5]
Hi Alma,

just wanted to let you know that, after running the setup.py, I needed to uninstall numba-0.50.0rc1-py3.8-linux-x86_64.egg, since it led to an module error for "test stereoscope". I got numba-0.49.1 via pip install and now the test was succesful.

Best regards,
Nik

**Comment by almaan** [comment]
Hello Nik!

Thank a heaps for reporting this, I really appreciate you letting me know! I've pushed some changes where I've updated the dependencies as well as changed some of the imports; now it should work fine with both of the `numba` versions you mention above.

If the issue persists or if you encounter any other problems, feel more than welcome to post them here!

Best
Alma

**Comment by nik1sto** [comment]
Thanks!
