### ISSUE TITLE
Bugfix in Utils

### ISSUE THREAD

**Issue by nik1sto** [almaan/stereoscope#6]
Hi Alma,

I encountered following error

stereoscope/lib/python3.8/site-packages/STereoSCope-0.2-py3.8.egg/stsc/utils.py", line 67, in <listcomp>
    index = index.append(pd.Index([str(k) + '&-' + x for \
TypeError: can only concatenate str (not "int") to str

and fixed it for myself so far by typecasting the x.

Best regards,
Nik

**Comment by almaan** [comment]
Hello Nik

Thanks a lot for reporting this, it's very appreciated!

New changes are pushed, where `x` is now cast as a string. Hopefully you should not get any errors now.

Best
Alma

**Comment by nik1sto** [comment]
Thank you!
