### ISSUE TITLE
Syntax Error stsc/datasets.py

### ISSUE THREAD

**Issue by nik1sto** [almaan/stereoscope#7]
Hi Alma,

I just wanted to install the most recent version and encountered for "stereoscope test" 

STereoSCope-0.3-py3.8.egg/stsc/datasets.py", line 292
    file = sys.stderr,
    ^
SyntaxError: invalid syntax 

due to a missing comma

Best regards,
Nik

**Comment by almaan** [comment]
Hi Nik

thanks for the report! I'm not sure why my linter didn't catch this (need to look into that..). But it should be taken care of now.

As always - tremendously happy for bringing this to my attention!

Good luck with the analyses, best
Alma

**Comment by nik1sto** [comment]
Thanks!
